# Unix V6++ Tongji 顶层构建脚本
#
# 创建于 2024年4月28日 上海市嘉定区
# by 2051565 GTY

.DEFAULT_GOAL := all

this-makefile := $(lastwork $(MAKEFILE_LIST))
export abs_srctree := $(realpath $(dir $(this-makefile)))
export abs_objtree := $(CURDIR)

.PHONY: help
help:
	@echo "unix-v6pp makefile"
	@echo "---------------"
	@echo "commands available:"
	@echo "- make bochs"
	@echo "    build and launch unix-v6pp using Bochs"
	@echo "- make qemu"
	@echo "    build and launch unix-v6pp using QEMU"
	@echo "- make qemug"
	@echo "    build and launch unix-v6pp using QEMU (with GDB)"
	@echo "- make"
	@echo "    alias for \"make all\""

.PHONY: deploy-full
deploy-full: build-full $(tools)
	mkdir -p target/img-workspace
	mkdir -p target/img-workspace/programs/bin
	mkdir -p target/img-workspace/programs/etc
	cp target/objs/kernel.bin target/img-workspace/
	cp target/objs/boot/boot.bin target/img-workspace/
	cp target/objs/apps/* target/img-workspace/programs/bin/
	cp target/objs/Shell.exe target/img-workspace/programs/
	cp tools/filescanner target/img-workspace/
	cp tools/FsEditor/fseditor target/img-workspace/
	cp tools/unixv6pp_splash/v6pp_splash.bmp target/img-workspace/programs/etc/
	cd target/img-workspace && ./filescanner | ./fseditor c.img c
	cp target/img-workspace/c.img target/

QEMU := qemu-system-i386 
QEMU += -m 64M 
QEMU += -rtc base=localtime 
QEMU += -d cpu_reset -D target/qemu.log 
QEMU += -machine pc 
QEMU += -cpu Icelake-Server 
QEMU += -enable-kvm 
QEMU_GDB := -chardev socket,path=target/qemu-gdb.sock,server=on,wait=off,id=gdb0 
QEMU_GDB += -gdb chardev:gdb0 -S 

QEMU_DISK := -boot c -drive file=target/c.img,if=ide,index=0,media=disk,format=raw


.PHONY: qemu-no-rebuild
qemu-no-rebuild:
	$(QEMU) $(QEMU_DISK)


.PHONY: qemug-no-rebuild
qemug-no-rebuild:
	$(QEMU) $(QEMU_DISK) $(QEMU_GDB)


.PHONY: qemu
qemu: deploy-full qemu-no-rebuild


.PHONY: qemug
qemug: deploy-full qemug-no-rebuild


.PHONY: clean
clean:
	rm -rf ./target
	rm -rf ./build


.PHONY: all
all: deploy-full
	@echo -e "\033[32mbuild success (unix-v6pp-tongji).\033[0m"


.PHONY: full
full: deploy-full
