include-path := $(CURDIR) $(abs_srctree)/fs

host-objs := FileSystemAdapter.o structures/SuperBlock.o structures/Inode.o structures/InodeDirectory.o main.o

include $(abs_srctree)/scripts/Makefile

HOSTCXXFLAGS += -std=c++20
